name: <i class="icon-beaker icon-fixed-width"></i> Experiments in Interactive Fiction
summary: A collection of [twee](http://www.gimcrackd.com/etc/src/) fic that thedeadparrot has written.
pygments: true
